CREATE TABLE STUDENT(
    STUDENT_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    GROUP INT NOT NULL
);

CREATE TABLE SUBJECT(
    SUBJECT_ID SERIAL PRIMARY KEY,
    SUBJECT_NAME VARCHAR(50) NOT NULL
);
CREATE TABLE EXAM_MARK(
    EXAM_MARK_ID SERIAL PRIMARY KEY,
    STUDENT_ID INT REFERENCES STUDENT(STUDENT_ID),
    SUBJECT_ID INT REFERENCES SUBJECT(SUBJECT_ID),
    MARK INT,
    CONSTRAINT PK_EXAM_MARK PRIMARY KEY(EXAM_MARK_ID)
);
CREATE TABLE EXAM(
    EXAM_ID SERIAL PRIMARY KEY,
    EXAM_DATE DATE,
    EXAM_TIME TIME
);

CREATE TABLE PREPARATION(
    PREPARATION_ID SERIAL PRIMARY KEY,
PREPARATION_METHOD VARCHAR(20) NOT NULL,
PREPARATION_EFFICIENCY INT CHECK (PREPARATION_EFFICIENCY BETWEEN 1 AND 5)
);
CREATE TABLE PREPARED(
PREPARED_ID SERIAL PRIMARY KEY,
STUDENT_ID INT REFERENCES STUDENT(STUDENT_ID),
PREPARED_SUBJECT INT REFERENCES SUBJECT(SUBJECT_ID),
PREPARED_METHOD INT REFERENCES PREPARATION(PREPARATION_ID),
CONSTRAINT PK_PREPARED PRIMARY KEY(PREPARED_ID)
);
CREATE TABLE PREPARATION_RESULT(
    PREPARATION_RESULT_ID SERIAL PRIMARY KEY,
PREPARED_ID INT NOT NULL REFERENCES PREPARED(PREPARED_ID),
EXAM_MARK_ID INT NOT NULL REFERENCES EXAM_MARK(EXAM_MARK_ID),
CONSTRAINT PK_PREPARATION_RESULT PRIMARY KEY(PREPARATION_RESULT_ID)
);
